# The weather forecast for Rexburg, Idaho on Tues, Feb 4, 2020
periods_that_start_with_a_day = [
    {
        'number' : 1,
        'name' : 'Today',
        'startTime' : '2020-02-04T11:00:00-07:00',
        'endTime' : '2020-02-04T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 17,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '7 mph',
        'windDirection' : 'W',
        'icon' : 'https://api.weather.gov/icons/land/day/few?size=medium',
        'shortForecast' : 'Sunny',
        'detailedForecast' : 'Sunny, with a high near 17. West wind around 7 mph.'
    },
    {
        'number' : 2,
        'name' : 'Tonight',
        'startTime' : '2020-02-04T18:00:00-07:00',
        'endTime' : '2020-02-05T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 2,
        'temperatureUnit' : 'F',
        'temperatureTrend' : 'rising',
        'windSpeed' : '8 mph',
        'windDirection' : 'S',
        'icon' : 'https://api.weather.gov/icons/land/night/snow,20/snow,40?size=medium',
        'shortForecast' : 'Chance Light Snow',
        'detailedForecast' : 'A chance of snow after 11pm. Mostly cloudy. Low around 2, with temperatures rising to around 8 overnight. Wind chill values as low as -6. South wind around 8 mph. Chance of precipitation is 40%. New snow accumulation of around one inch possible.'
    },
    {
        'number' : 3,
        'name' : 'Wednesday',
        'startTime' : '2020-02-05T06:00:00-07:00',
        'endTime' : '2020-02-05T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 21,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '7 to 12 mph',
        'windDirection' : 'S',
        'icon' : 'https://api.weather.gov/icons/land/day/snow,60?size=medium',
        'shortForecast' : 'Light Snow Likely',
        'detailedForecast' : 'Snow likely. Cloudy, with a high near 21. Wind chill values as low as -2. South wind 7 to 12 mph. Chance of precipitation is 60%. New snow accumulation of 1 to 3 inches possible.'
    },
    {
        'number' : 4,
        'name' : 'Wednesday Night',
        'startTime' : '2020-02-05T18:00:00-07:00',
        'endTime' : '2020-02-06T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 16,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '8 to 12 mph',
        'windDirection' : 'SSW',
        'icon' : 'https://api.weather.gov/icons/land/night/snow,60/snow,50?size=medium',
        'shortForecast' : 'Light Snow Likely',
        'detailedForecast' : 'Snow likely. Cloudy, with a low around 16. South southwest wind 8 to 12 mph. Chance of precipitation is 60%. New snow accumulation of 1 to 2 inches possible.'
    },
    {
        'number' : 5,
        'name' : 'Thursday',
        'startTime' : '2020-02-06T06:00:00-07:00',
        'endTime' : '2020-02-06T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 32,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '8 to 15 mph',
        'windDirection' : 'SW',
        'icon' : 'https://api.weather.gov/icons/land/day/snow,50/snow,40?size=medium',
        'shortForecast' : 'Chance Light Snow',
        'detailedForecast' : 'A chance of snow. Cloudy, with a high near 32. Southwest wind 8 to 15 mph, with gusts as high as 23 mph. Chance of precipitation is 50%. New snow accumulation of less than one inch possible.'
    },
    {
        'number' : 6,
        'name' : 'Thursday Night',
        'startTime' : '2020-02-06T18:00:00-07:00',
        'endTime' : '2020-02-07T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 25,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 to 9 mph',
        'windDirection' : 'SW',
        'icon' : 'https://api.weather.gov/icons/land/night/snow,50?size=medium',
        'shortForecast' : 'Chance Light Snow',
        'detailedForecast' : 'A chance of snow. Cloudy, with a low around 25. Chance of precipitation is 50%. New snow accumulation of around one inch possible.'
    },
    {
        'number' : 7,
        'name' : 'Friday',
        'startTime' : '2020-02-07T06:00:00-07:00',
        'endTime' : '2020-02-07T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 36,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '7 to 10 mph',
        'windDirection' : 'SW',
        'icon' : 'https://api.weather.gov/icons/land/day/snow,50/snow,30?size=medium',
        'shortForecast' : 'Chance Light Snow',
        'detailedForecast' : 'A chance of snow before 5pm. Mostly cloudy, with a high near 36. Chance of precipitation is 50%. New snow accumulation of less than one inch possible.'
    },
    {
        'number' : 8,
        'name' : 'Friday Night',
        'startTime' : '2020-02-07T18:00:00-07:00',
        'endTime' : '2020-02-08T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 23,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '7 mph',
        'windDirection' : 'S',
        'icon' : 'https://api.weather.gov/icons/land/night/bkn/snow,20?size=medium',
        'shortForecast' : 'Mostly Cloudy then Slight Chance Light Snow',
        'detailedForecast' : 'A slight chance of snow after 5am. Mostly cloudy, with a low around 23. Chance of precipitation is 20%.'
    },
    {
        'number' : 9,
        'name' : 'Saturday',
        'startTime' : '2020-02-08T06:00:00-07:00',
        'endTime' : '2020-02-08T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 36,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 to 10 mph',
        'windDirection' : 'S',
        'icon' : 'https://api.weather.gov/icons/land/day/snow,30?size=medium',
        'shortForecast' : 'Chance Light Snow',
        'detailedForecast' : 'A chance of snow. Mostly cloudy, with a high near 36. Chance of precipitation is 30%.'
    },
    {
        'number' : 10,
        'name' : 'Saturday Night',
        'startTime' : '2020-02-08T18:00:00-07:00',
        'endTime' : '2020-02-09T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 17,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 to 10 mph',
        'windDirection' : 'SSW',
        'icon' : 'https://api.weather.gov/icons/land/night/snow,20?size=medium',
        'shortForecast' : 'Slight Chance Light Snow',
        'detailedForecast' : 'A slight chance of snow. Mostly cloudy, with a low around 17. Chance of precipitation is 20%.'
    },
    {
        'number' : 11,
        'name' : 'Sunday',
        'startTime' : '2020-02-09T06:00:00-07:00',
        'endTime' : '2020-02-09T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 29,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 mph',
        'windDirection' : 'W',
        'icon' : 'https://api.weather.gov/icons/land/day/snow,20/bkn?size=medium',
        'shortForecast' : 'Slight Chance Light Snow then Partly Sunny',
        'detailedForecast' : 'A slight chance of snow before 11am. Partly sunny, with a high near 29. Chance of precipitation is 20%.'
    },
    {
        'number' : 12,
        'name' : 'Sunday Night',
        'startTime' : '2020-02-09T18:00:00-07:00',
        'endTime' : '2020-02-10T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 11,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 mph',
        'windDirection' : 'N',
        'icon' : 'https://api.weather.gov/icons/land/night/sct?size=medium',
        'shortForecast' : 'Partly Cloudy',
        'detailedForecast' : 'Partly cloudy, with a low around 11.'
    },
    {
        'number' : 13,
        'name' : 'Monday',
        'startTime' : '2020-02-10T06:00:00-07:00',
        'endTime' : '2020-02-10T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 28,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 mph',
        'windDirection' : 'NNE',
        'icon' : 'https://api.weather.gov/icons/land/day/few?size=medium',
        'shortForecast' : 'Sunny',
        'detailedForecast' : 'Sunny, with a high near 28.'
    },
    {
        'number' : 14,
        'name' : 'Monday Night',
        'startTime' : '2020-02-10T18:00:00-07:00',
        'endTime' : '2020-02-11T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 11,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 mph',
        'windDirection' : 'NE',
        'icon' : 'https://api.weather.gov/icons/land/night/sct?size=medium',
        'shortForecast' : 'Partly Cloudy',
        'detailedForecast' : 'Partly cloudy, with a low around 11.'
    }
]


# The weather forecast for Rexburg, Idaho on Monday evening, Feb 3, 2020
periods_that_start_with_a_night = [
    {
        'number' : 1,
        'name' : 'Tonight',
        'startTime' : '2020-02-10T18:00:00-07:00',
        'endTime' : '2020-02-11T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 11,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 mph',
        'windDirection' : 'NE',
        'icon' : 'https://api.weather.gov/icons/land/night/sct?size=medium',
        'shortForecast' : 'Partly Cloudy',
        'detailedForecast' : 'Partly cloudy, with a low around 11.'
    },
    {
        'number' : 2,
        'name' : 'Tuesday',
        'startTime' : '2020-02-04T11:00:00-07:00',
        'endTime' : '2020-02-04T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 17,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '7 mph',
        'windDirection' : 'W',
        'icon' : 'https://api.weather.gov/icons/land/day/few?size=medium',
        'shortForecast' : 'Sunny',
        'detailedForecast' : 'Sunny, with a high near 17. West wind around 7 mph.'
    },
    {
        'number' : 3,
        'name' : 'Tuesday Night',
        'startTime' : '2020-02-04T18:00:00-07:00',
        'endTime' : '2020-02-05T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 2,
        'temperatureUnit' : 'F',
        'temperatureTrend' : 'rising',
        'windSpeed' : '8 mph',
        'windDirection' : 'S',
        'icon' : 'https://api.weather.gov/icons/land/night/snow,20/snow,40?size=medium',
        'shortForecast' : 'Chance Light Snow',
        'detailedForecast' : 'A chance of snow after 11pm. Mostly cloudy. Low around 2, with temperatures rising to around 8 overnight. Wind chill values as low as -6. South wind around 8 mph. Chance of precipitation is 40%. New snow accumulation of around one inch possible.'
    },
    {
        'number' : 4,
        'name' : 'Wednesday',
        'startTime' : '2020-02-05T06:00:00-07:00',
        'endTime' : '2020-02-05T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 21,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '7 to 12 mph',
        'windDirection' : 'S',
        'icon' : 'https://api.weather.gov/icons/land/day/snow,60?size=medium',
        'shortForecast' : 'Light Snow Likely',
        'detailedForecast' : 'Snow likely. Cloudy, with a high near 21. Wind chill values as low as -2. South wind 7 to 12 mph. Chance of precipitation is 60%. New snow accumulation of 1 to 3 inches possible.'
    },
    {
        'number' : 5,
        'name' : 'Wednesday Night',
        'startTime' : '2020-02-05T18:00:00-07:00',
        'endTime' : '2020-02-06T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 16,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '8 to 12 mph',
        'windDirection' : 'SSW',
        'icon' : 'https://api.weather.gov/icons/land/night/snow,60/snow,50?size=medium',
        'shortForecast' : 'Light Snow Likely',
        'detailedForecast' : 'Snow likely. Cloudy, with a low around 16. South southwest wind 8 to 12 mph. Chance of precipitation is 60%. New snow accumulation of 1 to 2 inches possible.'
    },
    {
        'number' : 6,
        'name' : 'Thursday',
        'startTime' : '2020-02-06T06:00:00-07:00',
        'endTime' : '2020-02-06T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 32,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '8 to 15 mph',
        'windDirection' : 'SW',
        'icon' : 'https://api.weather.gov/icons/land/day/snow,50/snow,40?size=medium',
        'shortForecast' : 'Chance Light Snow',
        'detailedForecast' : 'A chance of snow. Cloudy, with a high near 32. Southwest wind 8 to 15 mph, with gusts as high as 23 mph. Chance of precipitation is 50%. New snow accumulation of less than one inch possible.'
    },
    {
        'number' : 7,
        'name' : 'Thursday Night',
        'startTime' : '2020-02-06T18:00:00-07:00',
        'endTime' : '2020-02-07T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 25,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 to 9 mph',
        'windDirection' : 'SW',
        'icon' : 'https://api.weather.gov/icons/land/night/snow,50?size=medium',
        'shortForecast' : 'Chance Light Snow',
        'detailedForecast' : 'A chance of snow. Cloudy, with a low around 25. Chance of precipitation is 50%. New snow accumulation of around one inch possible.'
    },
    {
        'number' : 8,
        'name' : 'Friday',
        'startTime' : '2020-02-07T06:00:00-07:00',
        'endTime' : '2020-02-07T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 36,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '7 to 10 mph',
        'windDirection' : 'SW',
        'icon' : 'https://api.weather.gov/icons/land/day/snow,50/snow,30?size=medium',
        'shortForecast' : 'Chance Light Snow',
        'detailedForecast' : 'A chance of snow before 5pm. Mostly cloudy, with a high near 36. Chance of precipitation is 50%. New snow accumulation of less than one inch possible.'
    },
    {
        'number' : 9,
        'name' : 'Friday Night',
        'startTime' : '2020-02-07T18:00:00-07:00',
        'endTime' : '2020-02-08T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 23,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '7 mph',
        'windDirection' : 'S',
        'icon' : 'https://api.weather.gov/icons/land/night/bkn/snow,20?size=medium',
        'shortForecast' : 'Mostly Cloudy then Slight Chance Light Snow',
        'detailedForecast' : 'A slight chance of snow after 5am. Mostly cloudy, with a low around 23. Chance of precipitation is 20%.'
    },
    {
        'number' : 10,
        'name' : 'Saturday',
        'startTime' : '2020-02-08T06:00:00-07:00',
        'endTime' : '2020-02-08T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 36,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 to 10 mph',
        'windDirection' : 'S',
        'icon' : 'https://api.weather.gov/icons/land/day/snow,30?size=medium',
        'shortForecast' : 'Chance Light Snow',
        'detailedForecast' : 'A chance of snow. Mostly cloudy, with a high near 36. Chance of precipitation is 30%.'
    },
    {
        'number' : 11,
        'name' : 'Saturday Night',
        'startTime' : '2020-02-08T18:00:00-07:00',
        'endTime' : '2020-02-09T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 17,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 to 10 mph',
        'windDirection' : 'SSW',
        'icon' : 'https://api.weather.gov/icons/land/night/snow,20?size=medium',
        'shortForecast' : 'Slight Chance Light Snow',
        'detailedForecast' : 'A slight chance of snow. Mostly cloudy, with a low around 17. Chance of precipitation is 20%.'
    },
    {
        'number' : 12,
        'name' : 'Sunday',
        'startTime' : '2020-02-09T06:00:00-07:00',
        'endTime' : '2020-02-09T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 29,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 mph',
        'windDirection' : 'W',
        'icon' : 'https://api.weather.gov/icons/land/day/snow,20/bkn?size=medium',
        'shortForecast' : 'Slight Chance Light Snow then Partly Sunny',
        'detailedForecast' : 'A slight chance of snow before 11am. Partly sunny, with a high near 29. Chance of precipitation is 20%.'
    },
    {
        'number' : 13,
        'name' : 'Sunday Night',
        'startTime' : '2020-02-09T18:00:00-07:00',
        'endTime' : '2020-02-10T06:00:00-07:00',
        'isDaytime' : False,
        'temperature' : 11,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 mph',
        'windDirection' : 'N',
        'icon' : 'https://api.weather.gov/icons/land/night/sct?size=medium',
        'shortForecast' : 'Partly Cloudy',
        'detailedForecast' : 'Partly cloudy, with a low around 11.'
    },
    {
        'number' : 14,
        'name' : 'Monday',
        'startTime' : '2020-02-10T06:00:00-07:00',
        'endTime' : '2020-02-10T18:00:00-07:00',
        'isDaytime' : True,
        'temperature' : 28,
        'temperatureUnit' : 'F',
        'temperatureTrend' : None,
        'windSpeed' : '6 mph',
        'windDirection' : 'NNE',
        'icon' : 'https://api.weather.gov/icons/land/day/few?size=medium',
        'shortForecast' : 'Sunny',
        'detailedForecast' : 'Sunny, with a high near 28.'
    }
]
