import tkinter as tk
import math


COLOR_NAMES = [
    'lightCoral',
    'indianRed1',
    'indianRed2',
    'indianRed',
    'indianRed3',
    'indianRed4',
    'firebrick1',
    'firebrick2',
    'firebrick3',
    'firebrick',
    'firebrick4',
    'red1',
    'red2',
    'red3',
    'red4',

    'rosyBrown1',
    'rosyBrown2',
    'rosyBrown3',
    'rosyBrown',
    'rosyBrown4',
    'brown1',
    'brown2',
    'brown3',
    'brown',
    'brown4',

    'tomato1',
    'tomato2',
    'tomato3',
    'tomato4',
    'coral',
    'coral1',
    'coral2',
    'coral3',
    'coral4',
    'salmon',
    'salmon1',
    'salmon2',
    'salmon3',
    'salmon4',

    'lightSalmon1',
    'lightSalmon2',
    'darkSalmon',
    'lightSalmon3',
    'lightSalmon4',
    'orangeRed1',
    'orangeRed2',
    'orangeRed3',
    'orangeRed4',
    'sienna1',
    'sienna2',
    'sienna3',
    'sienna',
    'sienna4',
    'chocolate1',
    'chocolate2',
    'chocolate',
    'chocolate3',
    'saddleBrown',

    'seashell',
    'seashell2',
    'seashell3',
    'seashell4',
    'peachPuff',
    'peachPuff2',
    'peachPuff3',
    'peachPuff4',
    'tan',
    'tan1',
    'sandyBrown',
    'tan2',
    'tan3',
    'tan4',

    'floralWhite',
    'linen',
    'oldLace',
    'antiqueWhite',
    'antiqueWhite1',
    'antiqueWhite2',
    'antiqueWhite3',
    'antiqueWhite4',
    'cornsilk',
    'cornsilk2',
    'cornsilk3',
    'cornsilk4',
    'bisque1',
    'bisque2',
    'bisque3',
    'bisque4',
    'burlywood1',
    'burlywood2',
    'burlywood3',
    'burlywood4',
    'burlywood',

    'blanchedAlmond',
    'papayaWhip',
    'moccasin',
    'navajoWhite',
    'navajoWhite2',
    'navajoWhite3',
    'navajoWhite4',
    'wheat',
    'wheat1',
    'wheat2',
    'wheat3',
    'wheat4',

    'orange',
    'orange2',
    'orange3',
    'orange4',
    'darkOrange',
    'darkOrange1',
    'darkOrange2',
    'darkOrange3',
    'darkOrange4',

    'paleGoldenrod',
    #'lightGoldenrod1',  # name is too long
    #'lightGoldenrod',  # similar to lightGoldenrod2
    #'lightGoldenrod2',  # name is too long
    #'lightGoldenrod3',  # name is too long
    #'lightGoldenrod4',  # name is too long
    'goldenrod1',
    'goldenrod2',
    'goldenrod',
    'goldenrod3',
    'goldenrod4',
    'darkGoldenrod1',
    'darkGoldenrod2',
    'darkGoldenrod3',
    'darkGoldenrod',
    'darkGoldenrod4',
    'gold1',
    'gold2',
    'gold3',
    'gold4',

    'lemonChiffon1',
    'lemonChiffon2',
    'lemonChiffon3',
    'lemonChiffon4',
    'khaki1',
    'khaki',
    'khaki2',
    'khaki3',
    'darkKhaki',
    'khaki4',
    'ivory1',
    'ivory2',
    'ivory3',
    'ivory4',

    #'lightGoldenrodYellow',  # name is too long
    'beige',
    'lightYellow1',
    'lightYellow2',
    'lightYellow3',
    #'lightYellow4',  similar to cornsilk4
    'yellow1',
    'yellow2',
    'yellow3',
    'yellow4',
    'oliveDrab1',
    'oliveDrab2',
    'oliveDrab3',
    'oliveDrab4',
    #'oliveDrab',  # similar to oliveDrab4
    #'darkOliveGreen1',  # name is too long
    #'darkOliveGreen2',  # name is too long
    #'darkOliveGreen3',  # name is too long
    #'darkOliveGreen4',  # name is too long
    'darkOliveGreen',
    'greenYellow',
    'lawnGreen',
    'limeGreen',
    'chartreuse',
    'chartreuse2',
    'chartreuse3',
    'chartreuse4',

    'mintCream',
    'honeydew1',
    'honeydew2',
    'honeydew3',
    'honeydew4',
    'seaGreen1',
    'seaGreen2',
    'seaGreen3',
    'mediumSeaGreen',
    'seaGreen',
    'darkSeaGreen1',
    'darkSeaGreen2',
    'darkSeaGreen3',
    'darkSeaGreen',
    'darkSeaGreen4',
    'paleGreen1',
    'paleGreen',
    'paleGreen2',
    'paleGreen3',
    'paleGreen4',
    'forestGreen',
    'green1',
    'green2',
    'green3',
    'green4',
    'green',
    'darkGreen',
    #'mediumSpringGreen',  # name is too long
    'springGreen1',
    'springGreen2',
    'springGreen3',
    'springGreen4',
    'aquamarine1',
    'aquamarine2',
    'aquamarine3',
    'aquamarine4',
    'azure1',
    'azure2',
    'azure3',
    'azure4',
    'paleTurquoise1',
    #'paleTurquoise',  # similar to paleTurquoise2
    'paleTurquoise2',
    'paleTurquoise3',
    'paleTurquoise4',
    'lightSeaGreen',
    'turquoise',
    'turquoise1',
    'turquoise2',
    #'mediumTurquoise',  # name is too long
    'darkTurquoise',
    'turquoise3',
    'turquoise4',
    'darkSlateGray1',
    'darkSlateGray2',
    'darkSlateGray3',
    'darkSlateGray4',
    'darkSlateGray',

    'lightCyan1',
    'lightCyan2',
    'lightCyan3',
    'lightCyan4',
    'cyan1',
    'cyan2',
    'cyan3',
    'cyan4',
    'cadetBlue1',
    'cadetBlue2',
    'cadetBlue3',
    'cadetBlue',
    'cadetBlue4',
    'ghostWhite',
    'aliceBlue',
    'powderBlue',
    'lightBlue1',
    'lightBlue',
    'lightBlue2',
    'lightBlue3',
    'lightBlue4',

    'deepSkyBlue',
    'deepSkyBlue2',
    'deepSkyBlue3',
    'deepSkyBlue4',
    'lightSkyBlue1',
    'lightSkyBlue2',
    'lightSkyBlue3',
    'lightSkyBlue4',
    'skyBlue',
    'skyBlue1',
    'lightSkyBlue',
    'skyBlue2',
    'skyBlue3',
    'skyBlue4',
    #'lightSteelBlue1',  # name is too long
    #'lightSteelBlue2',  # similar to slateGray2
    'lightSteelBlue',
    #'lightSteelBlue3',  # similar to slateGray3
    #'lightSteelBlue4',  # similar to slateGray4
    'steelBlue1',
    'steelBlue2',
    'steelBlue3',
    'steelBlue',
    'steelBlue4',

    'slateGray1',
    'slateGray2',
    'slateGray3',
    'lightSlateGray',
    'slateGray',
    'slateGray4',
    'dodgerBlue1',
    'dodgerBlue2',
    'dodgerBlue3',
    'dodgerBlue4',
    'cornflowerBlue',
    'royalBlue',
    'royalBlue1',
    'royalBlue2',
    'royalBlue3',
    'royalBlue4',
    'blue1',
    'blue2',
    'blue3',
    'blue4',
    'navyBlue',
    'midnightBlue',

    'lavender',
    #'lightSlateBlue',  # similar to slateBlue1
    'slateBlue1',
    #'mediumSlateBlue',  # similar to slateBlue2
    'slateBlue2',
    #'slateBlue',  # similar to slateBlue3
    'slateBlue3',
    'slateBlue4',
    #'darkSlateBlue',  # similar to slateBlue4
    'mediumPurple1',
    'mediumPurple2',
    'mediumPurple',
    'mediumPurple3',
    'mediumPurple4',
    'purple1',
    'purple2',
    'purple3',
    'purple4',
    'purple',
    'blueViolet',
    'darkViolet',
    'mediumOrchid1',
    'mediumOrchid2',
    'mediumOrchid',
    'mediumOrchid3',
    'mediumOrchid4',
    'darkOrchid1',
    'darkOrchid2',
    #'darkOrchid',  # similar to darkOrchid3
    'darkOrchid3',
    'darkOrchid4',

    'thistle1',
    'thistle2',
    'thistle',
    'thistle3',
    'thistle4',
    'plum1',
    'plum2',
    'plum',
    'plum3',
    'plum4',
    'violet',
    'magenta',
    'magenta2',
    'magenta3',
    'magenta4',
    'orchid1',
    'orchid2',
    'orchid',
    'orchid3',
    'orchid4',
    'maroon1',
    'maroon2',
    'maroon3',
    'maroon',
    'maroon4',
    'deepPink1',
    'deepPink2',
    'deepPink3',
    'deepPink4',
    'hotPink1',
    'hotPink',
    'hotPink2',
    'hotPink3',
    'hotPink4',
    'paleVioletRed1',
    'paleVioletRed',
    'paleVioletRed2',
    'paleVioletRed3',
    'paleVioletRed4',
    'violetRed1',
    'violetRed2',
    'violetRed',
    #'mediumVioletRed',  # name is too long
    'violetRed3',
    'violetRed4',
    'lavenderBlush1',
    'lavenderBlush2',
    'lavenderBlush3',
    'lavenderBlush4',

    'pink',
    'pink1',
    'pink2',
    'pink3',
    'pink4',
    'lightPink',
    'lightPink1',
    'lightPink2',
    'lightPink3',
    'lightPink4',
    'mistyRose1',
    'mistyRose2',
    'mistyRose3',
    'mistyRose4',
    'snow1',
    'snow2',
    'snow3',
    #'snow4',  # similar to gray54

    'white',
    'gray99',
    'gray98',
    'gray97',
    'gray96',
    'gray95',
    'gray94',
    'gray93',
    'gray92',
    'gray91',
    'gray90',
    'gray89',
    'gray88',
    'gray87',
    #'gainsboro',  # similar to gray86
    'gray86',
    'gray85',
    'gray84',
    'gray83',
    #'lightGray',  # similar to gray83
    'gray82',
    'gray81',
    'gray80',
    'gray79',
    'gray78',
    'gray77',
    'gray76',
    'gray75',
    'gray74',
    'gray73',
    'gray72',
    'gray71',
    'gray70',
    'gray69',
    'gray68',
    'gray67',
    #'darkGray',  # similar to gray66
    'gray66',
    'gray65',
    'gray64',
    'gray63',
    'gray62',
    'gray61',
    'gray60',
    'gray59',
    'gray58',
    'gray57',
    'gray56',
    'gray55',
    'gray54',
    'gray53',
    'gray52',
    'gray51',
    #'gray',  # similar to gray50
    'gray50',
    'gray49',
    'gray48',
    'gray47',
    'gray46',
    'gray45',
    'gray44',
    'gray43',
    'gray42',
    'gray41',
    'gray40',
    'gray39',
    'gray38',
    'gray37',
    'gray36',
    'gray35',
    'gray34',
    'gray33',
    'gray32',
    'gray31',
    'gray30',
    'gray29',
    'gray28',
    'gray27',
    'gray26',
    'gray25',
    'gray24',
    'gray23',
    'gray22',
    'gray21',
    'gray20',
    'gray19',
    'gray18',
    'gray17',
    'gray16',
    'gray15',
    'gray14',
    'gray13',
    'gray12',
    'gray11',
    'gray10',
    'gray9',
    'gray8',
    'gray7',
    'gray6',
    'gray5',
    'gray4',
    'gray3',
    'gray2',
    'gray1',
    'black'
]


def distance(rgb1, rgb2):
    dr = rgb2[0] - rgb1[0]
    dg = rgb2[1] - rgb1[1]
    db = rgb2[2] - rgb1[2]
    return math.ceil(math.sqrt(dr*dr + dg*dg + db*db))


def main():
    rgb_dict = {}
    NUM_ROWS = 53
    FONT_SIZE = 10  # font size in pixels
    HALF_INTENSITY = 2**15

    root = tk.Tk()
    root.title("Named Color Chart")
    row = 0
    col = 0
    ignore = 0
    thresh = 1000
    for color_name in COLOR_NAMES:
        if row >= ignore:
            rgb = root.winfo_rgb(color_name)
            if rgb in rgb_dict:
                print(f"Duplicate colors: {rgb_dict[rgb]} and {color_name}")
            else:
                for rgb1 in rgb_dict.keys():
                    dist = distance(rgb1, rgb)
                    if dist < thresh:
                        print(f"Similar colors ({dist}): {rgb_dict[rgb1]} and {color_name}")
                rgb_dict[rgb] = color_name
            print(rgb, color_name)

            intens = rgb[0] * 0.2989 + rgb[1] * 0.587 + rgb[2] * 0.1141
            fgcolor = 'black' if intens >= HALF_INTENSITY else 'white'
            elem = tk.Label(root, text=color_name,
                    bg=color_name, fg=fgcolor, font=(None, -FONT_SIZE))
            elem.grid(row=row-ignore, column=col, sticky=tk.E+tk.W)
        row += 1
        if color_name in ["plum4", "mistyRose4", "gray52"]:
            row += 1
        if (row == NUM_ROWS):
            row = 0
            col += 1

    print(f"Number of color names: {len(COLOR_NAMES)}", flush=True)
    root.mainloop()


main()
